services:
  mlflow-backend-store:
    image: postgres:14.0
    container_name: mlflow-backend-store
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "masterlabs", "-d", "modelpo"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow-artifact-store:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z
    container_name: mlflow-artifact-store
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - ./.env
    command: server /data/minio --console-address :9001
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow-server
    depends_on:
      mlflow-backend-store:
        condition: service_healthy
      mlflow-artifact-store:
        condition: service_healthy
    ports:
      - 5001:5000
    env_file:
      - ./.env

    command:
      - /bin/sh
      - -c
      - |
        mc config host add mlflowminio http://mlflow-artifact-store:9000 mastermino master1234! &&
        mc mb --ignore-existing mlflowminio/mlflow
        mlflow server \
        --backend-store-uri postgresql://masterlabs:master!1234@mlflow-backend-store/modelpo \
        --default-artifact-root s3://mlflow/ \
        --host 0.0.0.0